### PR TITLE
Add support to reset trained classifiers to their initial state

### PR DESCRIPTION
**Pull request by ibnesayeed**
I was preserving stopwords to restore on test teardown. However, if the Redis connection fails then the old stopwords were not available to restore. Changing order so that stopwords are cached before Redis connection fails, solved the issue.

### CODE REVIEW

**Comment by ibnesayeed** [comment]
Closed and reopened to trigger CI builds because some builds are failing due to Travis issue.

**Comment by ibnesayeed** [comment]
Finally, all the builds passed. It's safe and desired to be merged now.

**Comment by ibnesayeed** [comment]
Please don't merge it yet. I am pushing some more changes in it.

**Comment by Ch4s3** [comment]
Sounds good

**Comment by ibnesayeed** [comment]
This is done, please go ahead and merge it unless you have any code reviews.

**Comment by ibnesayeed** [comment]
Marking it done from my end.

**Comment by ibnesayeed** [comment]
@Ch4s3, I have resolved conflicts and it is ready to merge now.

**Comment by ibnesayeed** [comment]
@Ch4s3 is there anything blocking here in getting it merged? I was thinking of finalizing some other changes after my pending PRs are merged. I wanted to try to avoid dealing with multiple branches, that's why waiting everything to be merged.

**Comment by Ch4s3** [comment]
@ibnesayeed sorry, I was taking some time off from open source stuff for health reasons. It looks good!

**Pull request merged**
