### PR TITLE
Refactoring hasher

### PR DESCRIPTION
**Pull request by jcomello**
Hi,
I did some refactors at Hasher class and I wanna know what you think about it. 
I'm just used the inject method. for creating the hash without doing the: 
```ruby
hash = Hash.new
word.each do |w|
  ...
end
hash
```

If you like pls, let me know, and if you like it and are thinking a another refactor also let me know.

See ya

### CODE REVIEW

**Comment by parkr** [comment]
You might find that `inject` is much slower than `each` as it has to copy lots of memory then wait for it to be garbage collected.

Looks like there are some conflicts.

I'll defer to @Ch4s3 about this :)

**Comment by Ch4s3** [comment]
Yeah, I agree with @parkr, `each` is generally faster to use than inject in these cases. Check out [Fast Ruby](https://github.com/JuanitoFatas/fast-ruby), [this](https://github.com/JuanitoFatas/fast-ruby#enumerable) is loosely analogous. The other changes look good.

Also, sorry for the delay.

**Comment by Ch4s3** [comment]
@jcomello if you still want to get this merged, make that change on inject, rebase and I'll take another look!

**Comment by Ch4s3** [comment]
@jcomello Are you still interested in getting this merged?

**Comment by Ch4s3** [comment]
I'm closing this due to lack of activity. If you want to make the updates @jcomello, feel free to reopen it.

**Pull request closed without merging**
