### PR TITLE
Fix the corner cases

### PR DESCRIPTION
**Pull request by sueka**
I've tried doing

- avoid zero division & zero vector normalization
- prevent an indeterminate form from being generated (by `0.0 / 0.0` )

### CODE REVIEW

**Comment by Ch4s3** [comment]
@sueka Thanks for the PR!

If you can fix `NoMethodError: undefined method `zero?' for nil:NilClass`, I'll take a closer look.

**Comment by sueka** [comment]
@Ch4s3 

Fixed it.  I think there are two ways to fix the `NoMethodError`: the other is by using safe navigation operator to call `zero?` method.

**Comment by Ch4s3** [comment]
Again @sueka thanks a ton. Once we get this in I'll roll out a new gem version.

**Comment by sueka** [comment]
I've added tests against zero vector normalization and zero division errors.

**Comment by Ch4s3** [comment]
Awesome, thanks again for the great contribution!

**Pull request merged**
