### PR TITLE
add *very* basic stylechecks

### PR DESCRIPTION
**Pull request by alexanderadam**
This PR just integrates rubocop and relaxes some rubocop rules.
Additionally some of the rules are applied (basically `$ rubocop -a`).

### CODE REVIEW

**Comment by parkr** [comment]
Yeah, this code definitely could use improvement. I'm ok with this, but it's @Ch4s3's call.

Thanks @alexanderadam!

**Comment by Ch4s3** [comment]
Oh wow, some of those are much needed updates. Do we want to drop support for `1.9.3` in a minor version? Otherwise, I'm fine adding it in, and would even be cool making rubocop part of the contributing guide.

**Comment by Ch4s3** [comment]
On second thought, I don't see any reason to keep supporting 1.9.3

**Comment by alexanderadam** [comment]
@Ch4s3 I totally forgot to mention this: the included ` .hound.yml` can be used to activate [houndci](https://houndci.com/) for every PR. If everything from my PR is configured fine it should be green too. :wink: 

Anyway: thank you for merging.

**Comment by Ch4s3** [comment]
No worries @alexanderadam, we really like new contributors! I think I might activate hound!

**Pull request merged**
