### PR TITLE
Created a static site for documentation

### PR DESCRIPTION
**Pull request by ibnesayeed**
I have created a basic static documentation site. We need to add navigation among pages, currently only the home page links to other pages. The text is mostly the same as current README, except a few places that are modified to better unify the style. And in few places more text is added. In order for it to be served properly, the repo needs to be configured to serve static pages from the `docs` folder of the master branch. This idea was first tossed in #95.

### CODE REVIEW

**Comment by Ch4s3** [comment]
Does it make sense to do this in the same repo?

**Comment by ibnesayeed** [comment]
> Does it make sense to do this in the same repo?

Yes, absolutely! This way the maintenance will be a lot easier and timely. Also, I have made sure not to add any development dependency for this. The two gems required to build the page `jekyll` and `github-pages` are added in the Dockerfile, because the pages will be built by GitHub anyway. `docks/development.md file towards the bottom has documentation about how to run the docs in development environment.

**Comment by Ch4s3** [comment]
ok. This is setup to use /docs as the github pages source right?

**Comment by ibnesayeed** [comment]
Yes, master branch `/docs` folder.

**Comment by Ch4s3** [comment]
http://jekyll.github.io/classifier-reborn/ :+1:

**Comment by ibnesayeed** [comment]
Yay! It's live at http://jekyll.github.io/classifier-reborn/ now. :-)

**Comment by ibnesayeed** [comment]
Once there is better navigation established among pages of the documentation and sensitive matters such as mention of license etc. are verified then we can update README to point to that and remove all the inline clutter from the README.

**Pull request merged**
