### PR TITLE
README file cleaned up to point to the documentation site

### PR DESCRIPTION
**Pull request by ibnesayeed**
Only the essential getting started stuff along with repo status buttons are left in the README. For the rest of the content pointers are added to the documentation site.

### CODE REVIEW

**Comment by Ch4s3** [comment]
I probably want to leave some of this in the readme, so that people can check it out at a glance without having to go to a separate page. I'm open to removing some of the unnecessary stuff, but not all of it.

**Comment by ibnesayeed** [comment]
Finding that right balance was tricky for me. That's why I kept the Getting Started example to give a gist to visitors to get exited and get motivated to read more. Beyond that felt like too much duplication as the details of Bayes and LSI are not well narrated and simply add bulk to the README. However, if you feel there are some specific things that you would like to retain in the README or if you have any ideas of some new info, please feel free to share, but be more specific.

**Comment by Ch4s3** [comment]
Let's keep the code of conduct, and let's add a quick example of the Classifier and LSI, maybe 5 or 6 lines each.

**Comment by ibnesayeed** [comment]
I first thought the code of conduct only applies to contributors, that's why I moved it in the relevant documentation page. Now, I see that it also applies to issues, comments, wiki and whatnot, so it is worth keeping in the README. Would you prefer the text of the code of conduct to be present in README or just a link that points to that page?

There is already a quick example of the Bayes classifier, but I can add one for LSI as well. However, there is not much documented about the LSI, so it will be almost a complete copy of the code illustration on the documentation site.

On that note, I think authors can also remain in the README as a non-copyleft license makes no sense if the authors are not known.

**Comment by Ch4s3** [comment]
> Would you prefer the text of the code of conduct to be present in README or just a link that points to that page?

Let's keep the text. 

> On that note, I think authors can also remain in the README as a non-copyleft license makes no sense if the authors are not known.

Agreed.

**Comment by ibnesayeed** [comment]
There you have it. I tried to keep the LSI example simple and expressive while avoiding unnecessary tricks that might confuse beginners.

**Pull request merged**
