### PR TITLE
Abbility to add custom stopwords at classifier initialization

### LINKED ISSUE #125: Custom stopwords file during classifier initialization
Currently, the library ships with a list of stopwords in various languages. PR #73 adds the ability to specify more directories to look for stopwords. This means one can only add more stopwords, but can't overwrite it, except. perhaps by setting the value of `Hasher.STOPWORDS`. However, a stopwords list does not suit in all situations, for sepcial purpose collections stopwords are differnt in the same language. And in some case stopwords are not desired at all.

The current implementation also strongly relies on the name of the file being the language code.

In reality, one classifier instance is only tied with one language and each classifier may want to use its own stopwords. It would be nice to be able to pass an array of stopwords or an arbitrary file path during the initialization of the classifier that can overwrite the value of `Hasher.STOPWORDS[@language]`. I should be able to make a PR for this if we decide to go for it.

### PR DESCRIPTION
**Pull request by ibnesayeed**
This PR closes #125.

### CODE REVIEW

**Comment by Ch4s3** [comment]
Can you document this? Otherwise it looks good! 👍

**Comment by ibnesayeed** [comment]
Documenting this is easier, but writing tests is tricky as discussed in #130. Currently the scores are little unpredictable in presence and absence of stopwords.

**Comment by Ch4s3** [comment]
Throw some docs and a test on this and its good to go

**Comment by ibnesayeed** [comment]
Added tests and documented this and some other related changes that we made today. It is good for merging after code reviews.

**Comment by Ch4s3** [comment]
looks good

**Pull request merged**
