### PR TITLE
JRuby support!

### PR DESCRIPTION
**Pull request by mach-kernel**
Hi everyone,

I've been using this library's Bayes classifier for a while and didn't really see any reason why it wasn't possible to use in JRuby other than the dependency of `fast_stemmer`. I found that someone made a wrapper around the [Porter Stemmer](https://tartarus.org/martin/PorterStemmer/) reference. I'm using [my fork](https://github.com/mach-kernel/jruby-stemmer) because of some import issues, but otherwise it is unchanged from the original. 

It appears that all the tests pass. I am happy to test other functionality and write some docs for this.

Thanks much!

### CODE REVIEW

**Comment by Ch4s3** [comment]
@mach-kernel Awesome! Thanks for the contribution. Could you remove the change to `lib/classifier-reborn/version.rb` I'll bump the version on the next release. Could you also update the docs with any necessary setup or general info about jRuby usage?

**Comment by mach-kernel** [comment]
@Ch4s3 Travis seems to be happy now, I made the requested changes. As for the gem, I think you can push out different versions per platform and retain the same name but it's difficult to orchestrate. Note that the other `*.gemspec` has a gem name of `classifier-reborn-jruby`. Otherwise, everything else, including `require 'classifier-reborn'` should work business as usual.

**Comment by Ch4s3** [comment]
Excellent! I'll take a look tomorrow

**Comment by Ch4s3** [comment]
Thanks @mach-kernel! I'll try to roll a release soon.

**Pull request merged**
