### PR TITLE
Update bayes.rb

### PR DESCRIPTION
**Pull request by MadBomber**
Added ability to handle an array of classifications to the constructor.

with this patch you can now do things like:
```ruby
Pathname.pwd.children.select{|c| c if c.directory?}.each do |dir|
  category                = dir.basename.to_s.downcase
  category_hash[category] = dir
end

classifier = ClassifierReborn::Bayes.new(category_hash.keys)
```

### CODE REVIEW

**Comment by Ch4s3** [comment]
@MadBomber can you include the example in the read me? @parkr I think this is fine, but do you think it needs any additional tests?

**Comment by MadBomber** [comment]
Okay I will update the README and look at adding a test.  It may be a day or two before I get back into it.

**Comment by parkr** [comment]
Yeah this will require a test. I wonder if folks use arrays for the category key. I can't imagine they do, but I can't say definitively one way or another.

**Comment by MadBomber** [comment]
Well that was my nights entertainment.  I didn't test the tests.  I also notice at least one typo in a string that didn't make sense in English.   #train 'Ruby', 'I sweet language'   .... like what does that mean.

Dewayne
  o-*

**Comment by Ch4s3** [comment]
Yeah, I've personally written code that does something similar to this, but from outside of the gem, so I like it. Once this passes tests, I'd be happy to merge it in. Then I think we need to address #42 and get a `2.0.4` out.

**Comment by MadBomber** [comment]
just pushed a typo fix to the test file.  tests are passing.  ought to consider updating from test-unit to minitest

**Comment by Ch4s3** [comment]
Agreed on minitest, I'll add it to the list on #42.

**Pull request merged**
